In [1]:
import numpy as np

In [5]:
array = np.array([[10,20,30],
                  [40,50,60],
                  [70,80,90]])
print(array.ndim)
print(array.shape)
array


2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [6]:
elemento = array[1,2]
elemento

np.int64(60)

In [7]:
linha_0 = array[0]
linha_0

array([10, 20, 30])

In [8]:
coluna_1 = array[:,1]
coluna_1

array([20, 50, 80])

In [12]:
subarray = array[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [13]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])