In [1]:
import numpy as np

In [4]:
array = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15],
                 [16, 17, 18, 19, 20]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
fatiando_linhas = array[0:2,:]
fatiando_linhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
fatiando_3_colunas = array[:, 0:3]
fatiando_3_colunas

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [12]:
subarray_central = array[1:3, 1:3]
subarray_central

array([[ 7,  8],
       [12, 13]])

In [15]:
subarray_lateral = array[2:4, 2:5] 
subarray_lateral

array([[13, 14, 15],
       [18, 19, 20]])