In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
#adição
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [4]:
#subtração
subtracao = np.subtract(array, 5)
subtracao

array([-4, -3, -2, -1,  0])

In [5]:
#multiplicação
multiplicacao = np.multiply(array, 2)
multiplicacao

array([ 2,  4,  6,  8, 10])

In [6]:
#divisão
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [7]:
media = np.mean(array)
media

np.float64(3.0)

In [8]:
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [9]:
comparação_maior_que_3 = np.greater(array, 3)
comparação_maior_que_3

array([False, False, False,  True,  True])

In [10]:
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [11]:
arredondamento = np.round(array, 3)
arredondamento

array([1, 2, 3, 4, 5])