In [1]:
import numpy as np

In [28]:
array_original = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array_view = array_original[1:, 1:]
array_view

array([[5, 6],
       [8, 9]])

In [30]:
array_view[0,0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [31]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [25]:
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [26]:
array_copia[0,0] = 100
array_copia

array([[100,   2,   3],
       [  4,  99,   6],
       [  7,   8,   9]])

In [27]:
array_original


array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])